sudo: required
sevices:
  - docker

before_install:
  - docker build -t bui1der/docker-react -f Dockerfile.dev .

script:
  - docker run bui1der/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-004829846714"
  docker_path: "docker"
  on:
    baranch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY